// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: poSKmt1KMDoYUF6h3Y78GP
// Component: CLQCtcSPhDgmH

import * as React from "react";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Header from "../../Header"; // plasmic-import: wS2ddgETNt58W/component
import Button from "../../Button"; // plasmic-import: kC2F6N1O7TYTuM/component
import ProductCard from "../../ProductCard"; // plasmic-import: I9bSXDVKP-_xia/component
import Ratings from "../../Ratings"; // plasmic-import: RJoD3U13gzPVxR/component
import FeatureItem from "../../FeatureItem"; // plasmic-import: 6yeDc8BOoSwsCq/component
import BlogPost from "../../BlogPost"; // plasmic-import: XtW6OFg7bRL4Bi/component
import Footer from "../../Footer"; // plasmic-import: d3WHbEehslF7mk/component
import ProductRow from "../../ProductRow"; // plasmic-import: FaWqiAMedvRmIf/component

import { useScreenVariants as useScreenVariantsgW35LCmK5FyoDz } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: gW35LCmK5FYODz/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_library_plasmic_color_type_css from "../library_plasmic_color_type/plasmic_library_plasmic_color_type.module.css"; // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss
import projectcss from "./plasmic_paradosiaki_agiografia.module.css"; // plasmic-import: poSKmt1KMDoYUF6h3Y78GP/projectcss
import sty from "./PlasmicHome.module.css"; // plasmic-import: CLQCtcSPhDgmH/css

import ChecksvgIcon from "./icons/PlasmicIcon__Checksvg"; // plasmic-import: CXbqs2YSSg-hSz/icon
import ButtonArrowIcon from "./icons/PlasmicIcon__ButtonArrow"; // plasmic-import: PBYxdjRw4Gq0L2/icon
import DotCircleOIcon from "./icons/PlasmicIcon__DotCircleO"; // plasmic-import: EzJBJEGXuf3HeO/icon
import galinaNMiziNqvJx5MUnsplashjpgOj5FljDOxLgsNc from "./images/galinaNMiziNqvJx5MUnsplashjpg.jpg"; // plasmic-import: Oj5FljDOxLgsNC/picture
import igorSonFvPxCqgtwcUnsplashjpgDCWmzzZg7Jm1Ma from "./images/igorSonFvPxCqgtwcUnsplashjpg.jpg"; // plasmic-import: dCWmzzZg7Jm1MA/picture
import scottWebbORwRlTgBrPoUnsplashjpgK9B4Oe5CUewWz9 from "./images/scottWebbORwRlTgBrPoUnsplashjpg.jpg"; // plasmic-import: K9b4OE5CUewWZ9/picture
import freddieMarriageUcfKyTanLuUnsplashjpgSBkLuiwh6WxZe from "./images/freddieMarriageUcfKyTanLuUnsplashjpg.jpg"; // plasmic-import: SBkLuiwh-6wxZe/picture
import f18160GiZtf60VRv from "./images/f1.jpg"; // plasmic-import: 8160giZTF60vRV/picture
import f2HWMyZlVdy36Uxv from "./images/f2.jpg"; // plasmic-import: hWMyZLVdy36Uxv/picture
import f3CyKtk6OS2HjTfn from "./images/f3.jpg"; // plasmic-import: CyKTK6oS2HjTFN/picture
import f4MJjaldZdX2J0Ba from "./images/f4.jpg"; // plasmic-import: MJjaldZdX2J0Ba/picture
import b1ElV8NLvtMmEbJk from "./images/b1.jpg"; // plasmic-import: ElV8nLvtMMEbJk/picture
import b2CiXwhWWe0BHWc5 from "./images/b2.jpg"; // plasmic-import: CIXwhWWe0bHWc5/picture
import b3C6EpQzQg4ZOkm from "./images/b3.jpg"; // plasmic-import: c-6epQZQg4ZOkm/picture
import adidasNarnke4I0KdH from "./images/adidas.png"; // plasmic-import: NARNKE4_I0KD_H/picture
import hmZLzhFken3EtDtf from "./images/hm.png"; // plasmic-import: zLZHFken3etDtf/picture
import kappa1JEXpQ77XoIuTh from "./images/kappa.png"; // plasmic-import: 1jEXpQ77xoIuTh/picture
import lacosteJi0LZ1593W10 from "./images/lacoste.png"; // plasmic-import: Ji0l_z159-3W10/picture
import levisR9MIrqDlMzqOq from "./images/levis.png"; // plasmic-import: r9mIrqDLMzq_oq/picture
import εικόναViber20230528192315013JpgRYl0QrkO from "./images/\u03B5\u03B9\u03BA\u03CC\u03BD\u03B1Viber20230528192315013Jpg.jpg"; // plasmic-import: rYl0Qrk-o/picture
import εικόναViber20230528192252553JpgAaitj7J6 from "./images/\u03B5\u03B9\u03BA\u03CC\u03BD\u03B1Viber20230528192252553Jpg.jpg"; // plasmic-import: AAITJ7-J6/picture
import εικόναViber20230528192329511JpgGpDqcvMYw from "./images/\u03B5\u03B9\u03BA\u03CC\u03BD\u03B1Viber20230528192329511Jpg.jpg"; // plasmic-import: GpDqcvMYw/picture
import εικόναViber20230528192335684Jpg1QfqyDkR4 from "./images/\u03B5\u03B9\u03BA\u03CC\u03BD\u03B1Viber20230528192335684Jpg.jpg"; // plasmic-import: 1QFQYDkR4/picture
import εικόναViber20230528192319388JpgS29Ybr8Ni from "./images/\u03B5\u03B9\u03BA\u03CC\u03BD\u03B1Viber20230528192319388Jpg.jpg"; // plasmic-import: S29ybr8ni/picture
import εικόναViber20230528192327087JpgUwCblxZh from "./images/\u03B5\u03B9\u03BA\u03CC\u03BD\u03B1Viber20230528192327087Jpg.jpg"; // plasmic-import: UwCBLXZh_/picture
import εικόναViber20230528192744264JpgET6CzJx2V from "./images/\u03B5\u03B9\u03BA\u03CC\u03BD\u03B1Viber20230528192744264Jpg.jpg"; // plasmic-import: eT6CZJx2v/picture
import εικόναViber20230528192325218Jpg45Gob19Rq from "./images/\u03B5\u03B9\u03BA\u03CC\u03BD\u03B1Viber20230528192325218Jpg.jpg"; // plasmic-import: 45GOB19rq/picture

export type PlasmicHome__VariantMembers = {};
export type PlasmicHome__VariantsArgs = {};
type VariantPropType = keyof PlasmicHome__VariantsArgs;
export const PlasmicHome__VariantProps = new Array<VariantPropType>();

export type PlasmicHome__ArgsType = {};
type ArgPropType = keyof PlasmicHome__ArgsType;
export const PlasmicHome__ArgProps = new Array<ArgPropType>();

export type PlasmicHome__OverridesType = {
  root?: p.Flex<"div">;
  button?: p.Flex<typeof Button>;
  featureItem?: p.Flex<typeof FeatureItem>;
  bestSellers?: p.Flex<"div">;
  productRow?: p.Flex<typeof ProductRow>;
  bigPlants?: p.Flex<"div">;
  cactuses?: p.Flex<"div">;
};

export interface DefaultHomeProps {
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicHome__RenderFunc(props: {
  variants: PlasmicHome__VariantsArgs;
  args: PlasmicHome__ArgsType;
  overrides: PlasmicHome__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsgW35LCmK5FyoDz()
  });

  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_library_plasmic_color_type_css.plasmic_tokens,
            sty.root
          )}
        >
          <div className={classNames(projectcss.all, sty.freeBox__zwmA0)}>
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__aiSs5)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__l5Uy8)}>
                <Header
                  className={classNames("__wab_instance", sty.header___5BPml)}
                />

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__esV0S)}
                >
                  <h1
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1___4ZjJm
                    )}
                  >
                    {"Παραδοσιακή Αγιογραφία"}
                  </h1>
                  <h1
                    className={classNames(
                      projectcss.all,
                      projectcss.h1,
                      projectcss.__wab_text,
                      sty.h1__eg1Xx
                    )}
                  >
                    {
                      "Καλως Ηλθατε Στο Εργαστηρι μας,\nΣας Ευχαριστουμε που ειστε εδω"
                    }
                  </h1>
                  <Button
                    data-plasmic-name={"button"}
                    data-plasmic-override={overrides.button}
                    className={classNames("__wab_instance", sty.button)}
                    submitsForm={true}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__t0Spk
                      )}
                    >
                      {"Δείτε Εικόνες"}
                    </div>
                    <ButtonArrowIcon
                      className={classNames(projectcss.all, sty.svg__z0Mob)}
                      role={"img"}
                    />
                  </Button>
                </p.Stack>
              </div>
            </p.Stack>
            {true ? (
              <div className={classNames(projectcss.all, sty.freeBox__b1BaL)}>
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__mjH2
                  )}
                >
                  {"Top Collections"}
                </h2>
              </div>
            ) : null}
            {true ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns___2Zouw)}
              >
                <div className={classNames(projectcss.all, sty.column__ap8Qp)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__wsNzy
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__spyS8)}
                        displayHeight={"100%" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"none" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        src={{
                          src: galinaNMiziNqvJx5MUnsplashjpgOj5FljDOxLgsNc,
                          fullWidth: 1920,
                          fullHeight: 1278,
                          aspectRatio: undefined
                        }}
                      />
                    }
                    onSale={true}
                    price={"$65.00"}
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings___3AlSz
                        )}
                        numReviews={"(45 Review)"}
                      />
                    }
                    title={"Product"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__cfNvI)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__lXzWf
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__mpQpa)}
                        displayHeight={"100%" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"none" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        src={{
                          src: igorSonFvPxCqgtwcUnsplashjpgDCWmzzZg7Jm1Ma,
                          fullWidth: 640,
                          fullHeight: 481,
                          aspectRatio: undefined
                        }}
                      />
                    }
                    onSale={true}
                    price={"$80.00"}
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings__yv0K5
                        )}
                        numReviews={"(45 Review)"}
                      />
                    }
                    title={"Product"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column___4ZeRf)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__dn1Fr
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__v26X)}
                        displayHeight={"100%" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"none" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        src={{
                          src: scottWebbORwRlTgBrPoUnsplashjpgK9B4Oe5CUewWz9,
                          fullWidth: 1920,
                          fullHeight: 1280,
                          aspectRatio: undefined
                        }}
                      />
                    }
                    price={"$40.00"}
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings__zSzb
                        )}
                        numReviews={"(45 Review)"}
                      />
                    }
                    title={"Product"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__soe7J)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__jefE5
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img___16Jo)}
                        displayHeight={"100%" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"none" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        src={{
                          src: freddieMarriageUcfKyTanLuUnsplashjpgSBkLuiwh6WxZe,
                          fullWidth: 640,
                          fullHeight: 427,
                          aspectRatio: undefined
                        }}
                      />
                    }
                    onSale={true}
                    price={"$100.00"}
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings__yGTec
                        )}
                        numReviews={"(45 Review)"}
                      />
                    }
                    title={"Product"}
                  />
                </div>
              </p.Stack>
            ) : null}
            {true ? (
              <FeatureItem
                data-plasmic-name={"featureItem"}
                data-plasmic-override={overrides.featureItem}
                className={classNames("__wab_instance", sty.featureItem)}
              />
            ) : null}
            {true ? (
              <div className={classNames(projectcss.all, sty.freeBox__dt2Tk)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___32S2O
                  )}
                >
                  {"Featured Products"}
                </div>
              </div>
            ) : null}
            {true ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns__tRps)}
              >
                <div className={classNames(projectcss.all, sty.column___1HlEx)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__hgWxX
                    )}
                    price={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___6M3Yd
                        )}
                      >
                        {"$160.00"}
                      </div>
                    }
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings__irBa2
                        )}
                        numReviews={"(12 Review)"}
                        stars={"two" as const}
                      />
                    }
                    title={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__o3Nbj
                        )}
                      >
                        {"Designed Sofa"}
                      </div>
                    }
                    withReviews={true}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__eMSo)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__w5RGh
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__qdUvA)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"none" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        src={{
                          src: f2HWMyZlVdy36Uxv,
                          fullWidth: 270,
                          fullHeight: 310,
                          aspectRatio: undefined
                        }}
                      />
                    }
                    price={"$200.00"}
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings__rljeo
                        )}
                        stars={"four" as const}
                      />
                    }
                    title={"Dining Table"}
                    withReviews={true}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__kLmNh)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__wuryt
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__c4TyI)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"none" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        src={{
                          src: f3CyKtk6OS2HjTfn,
                          fullWidth: 270,
                          fullHeight: 310,
                          aspectRatio: undefined
                        }}
                      />
                    }
                    price={"$100.00"}
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings__jisZp
                        )}
                        numReviews={"(23 Review)"}
                        stars={"five" as const}
                      />
                    }
                    title={"Chair and Table"}
                    withReviews={true}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__etL7T)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__upyWg
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img___6KGk8)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"none" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        src={{
                          src: f4MJjaldZdX2J0Ba,
                          fullWidth: 270,
                          fullHeight: 310,
                          aspectRatio: undefined
                        }}
                      />
                    }
                    price={"$299.00"}
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings___3S1N0
                        )}
                        numReviews={"(35 Review)"}
                      />
                    }
                    title={"Modern Arm Chair"}
                    withReviews={true}
                  />
                </div>
              </p.Stack>
            ) : null}
            {true ? (
              <div className={classNames(projectcss.all, sty.freeBox__c9RD)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__uGztc
                  )}
                >
                  {"Latest Blog"}
                </div>
              </div>
            ) : null}
            {true ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns__xAQot)}
              >
                <div className={classNames(projectcss.all, sty.column__dy5Pt)}>
                  <BlogPost
                    className={classNames(
                      "__wab_instance",
                      sty.blogPost__rHsgK
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__bxlL0)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"none" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        src={{
                          src: b1ElV8NLvtMmEbJk,
                          fullWidth: 370,
                          fullHeight: 250,
                          aspectRatio: undefined
                        }}
                      />
                    }
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__xQgl)}>
                  <BlogPost
                    className={classNames(
                      "__wab_instance",
                      sty.blogPost__jxZlh
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__p7KrH)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"none" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        src={{
                          src: b2CiXwhWWe0BHWc5,
                          fullWidth: 370,
                          fullHeight: 250,
                          aspectRatio: undefined
                        }}
                      />
                    }
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__azDy9)}>
                  <BlogPost
                    className={classNames(
                      "__wab_instance",
                      sty.blogPost__czBhp
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__ysSth)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"none" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        src={{
                          src: b3C6EpQzQg4ZOkm,
                          fullWidth: 370,
                          fullHeight: 250,
                          aspectRatio: undefined
                        }}
                      />
                    }
                  />
                </div>
              </p.Stack>
            ) : null}
            {true ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__tkq6D)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__akiwr)}
                  displayHeight={"60px" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"none" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"90px" as const}
                  src={{
                    src: adidasNarnke4I0KdH,
                    fullWidth: 90,
                    fullHeight: 60,
                    aspectRatio: undefined
                  }}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img___6ON0I)}
                  displayHeight={"60px" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"none" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"91px" as const}
                  src={{
                    src: hmZLzhFken3EtDtf,
                    fullWidth: 91,
                    fullHeight: 60,
                    aspectRatio: undefined
                  }}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__gM7Sb)}
                  displayHeight={"60px" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"none" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"98px" as const}
                  src={{
                    src: kappa1JEXpQ77XoIuTh,
                    fullWidth: 98,
                    fullHeight: 60,
                    aspectRatio: undefined
                  }}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__dwNiG)}
                  displayHeight={"60px" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"none" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"124px" as const}
                  src={{
                    src: lacosteJi0LZ1593W10,
                    fullWidth: 124,
                    fullHeight: 60,
                    aspectRatio: undefined
                  }}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__rnYe)}
                  displayHeight={"60px" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"none" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"125px" as const}
                  src={{
                    src: levisR9MIrqDlMzqOq,
                    fullWidth: 125,
                    fullHeight: 60,
                    aspectRatio: undefined
                  }}
                />
              </p.Stack>
            ) : null}
            {true ? (
              <Footer
                className={classNames("__wab_instance", sty.footer__pTkIp)}
              />
            ) : null}
          </div>
          <p.Stack
            as={"div"}
            data-plasmic-name={"bestSellers"}
            data-plasmic-override={overrides.bestSellers}
            hasGap={true}
            className={classNames(projectcss.all, sty.bestSellers)}
          >
            {true ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__jKg5Z)}
              >
                <DotCircleOIcon
                  className={classNames(projectcss.all, sty.svg__r8Awh)}
                  role={"img"}
                />

                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__tLqnq
                  )}
                >
                  {"Παραδοσιακη Τεχνικη Αγιογραφιας"}
                </h2>
              </p.Stack>
            ) : null}
            {true ? (
              <ProductRow
                data-plasmic-name={"productRow"}
                data-plasmic-override={overrides.productRow}
                className={classNames("__wab_instance", sty.productRow)}
              />
            ) : null}
          </p.Stack>
          <p.Stack
            as={"div"}
            data-plasmic-name={"bigPlants"}
            data-plasmic-override={overrides.bigPlants}
            hasGap={true}
            className={classNames(projectcss.all, sty.bigPlants)}
          >
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__yoLoV)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__gTUg)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__d7FZl)}
                  displayHeight={
                    "270px /* plasmic-token: PE1QFaZ5ZFDg60 */" as const
                  }
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"100%" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"100%" as const}
                  loading={"lazy" as const}
                  src={{
                    src: εικόναViber20230528192315013JpgRYl0QrkO,
                    fullWidth: 1200,
                    fullHeight: 1600,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__o7YtA)}>
                  <a
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__rvoLa
                    )}
                  >
                    {"Παναγία Η Οδηγήτρια"}
                  </a>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ey60C
                    )}
                  >
                    {"ΛΙΓΑ ΛΟΓΙΑ"}
                  </div>
                </div>
              </p.Stack>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__h2Ibm)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__bvu9O)}
                  displayHeight={
                    "270px /* plasmic-token: PE1QFaZ5ZFDg60 */" as const
                  }
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"100%" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"100%" as const}
                  loading={"lazy" as const}
                  src={{
                    src: εικόναViber20230528192252553JpgAaitj7J6,
                    fullWidth: 1200,
                    fullHeight: 1600,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__cSe1E)}>
                  <a
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__et4Lf
                    )}
                  >
                    {"Παναγία η Δέσποινα"}
                  </a>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__sGrH2
                    )}
                  >
                    {"ΛΙΓΑ ΛΟΓΙΑ"}
                  </div>
                </div>
              </p.Stack>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__gJh8Z)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__m2EAx)}
                  displayHeight={
                    "270px /* plasmic-token: PE1QFaZ5ZFDg60 */" as const
                  }
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"100%" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"100%" as const}
                  loading={"lazy" as const}
                  src={{
                    src: εικόναViber20230528192329511JpgGpDqcvMYw,
                    fullWidth: 1200,
                    fullHeight: 1600,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__nir0Z)}>
                  <a
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__j4SAw
                    )}
                  >
                    {"Παναγία Η Δεομένη"}
                  </a>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__oeQdz
                    )}
                  >
                    {"ΛΙΓΑ ΛΟΓΙΑ"}
                  </div>
                </div>
              </p.Stack>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__nDdUw)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__bmhcw)}
                  displayHeight={
                    "270px /* plasmic-token: PE1QFaZ5ZFDg60 */" as const
                  }
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"100%" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"100%" as const}
                  loading={"lazy" as const}
                  src={{
                    src: εικόναViber20230528192335684Jpg1QfqyDkR4,
                    fullWidth: 1200,
                    fullHeight: 1600,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__v3OjI)}>
                  <a
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__se12A
                    )}
                  >
                    {"Παναγία"}
                  </a>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__kN1
                    )}
                  >
                    {"ΛΙΓΑ ΛΟΓΙΑ"}
                  </div>
                </div>
              </p.Stack>
            </p.Stack>
          </p.Stack>
          <p.Stack
            as={"div"}
            data-plasmic-name={"cactuses"}
            data-plasmic-override={overrides.cactuses}
            hasGap={true}
            className={classNames(projectcss.all, sty.cactuses)}
          >
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns___6X8MV)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__q4D07)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__slXib)}
                  displayHeight={
                    "270px /* plasmic-token: PE1QFaZ5ZFDg60 */" as const
                  }
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"100%" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"100%" as const}
                  loading={"lazy" as const}
                  src={{
                    src: εικόναViber20230528192319388JpgS29Ybr8Ni,
                    fullWidth: 1200,
                    fullHeight: 1600,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__yR8Ib)}>
                  <a
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__dMg2N
                    )}
                  >
                    {"Άγιος Ιωάννης Ο Πρόδρομμος"}
                  </a>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__xraec
                    )}
                  >
                    {"ΛΙΓΑ ΛΟΓΙΑ"}
                  </div>
                </div>
              </p.Stack>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__zEbZp)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__kgBg1)}
                  displayHeight={
                    "270px /* plasmic-token: PE1QFaZ5ZFDg60 */" as const
                  }
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"100%" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"100%" as const}
                  loading={"lazy" as const}
                  src={{
                    src: εικόναViber20230528192327087JpgUwCblxZh,
                    fullWidth: 1200,
                    fullHeight: 1600,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__cQphW)}>
                  <a
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__za8Hr
                    )}
                  >
                    {"'Αγιος Αθανάσιος"}
                  </a>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__zJdP7
                    )}
                  >
                    {"ΛΙΓΑ ΛΟΓΙΑ"}
                  </div>
                </div>
              </p.Stack>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__zSiId)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img___88Dvm)}
                  displayHeight={
                    "270px /* plasmic-token: PE1QFaZ5ZFDg60 */" as const
                  }
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"100%" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"100%" as const}
                  loading={"lazy" as const}
                  src={{
                    src: εικόναViber20230528192744264JpgET6CzJx2V,
                    fullWidth: 1200,
                    fullHeight: 1600,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__wNwXi)}>
                  <a
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__qXazo
                    )}
                  >
                    {"Άγιος Χαράλαμπος"}
                  </a>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__wUwYv
                    )}
                  >
                    {"ΛΙΓΑ ΛΟΓΙΑ"}
                  </div>
                </div>
              </p.Stack>
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.column__pGzZm)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img___1X8Qa)}
                  displayHeight={
                    "270px /* plasmic-token: PE1QFaZ5ZFDg60 */" as const
                  }
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"100%" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"100%" as const}
                  loading={"lazy" as const}
                  src={{
                    src: εικόναViber20230528192325218Jpg45Gob19Rq,
                    fullWidth: 1200,
                    fullHeight: 1600,
                    aspectRatio: undefined
                  }}
                />

                <div className={classNames(projectcss.all, sty.freeBox__eFvvF)}>
                  <a
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__dkcnp
                    )}
                  >
                    {"Αρχάγγελος Μιχαήλ"}
                  </a>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__l2Ct
                    )}
                  >
                    {"ΛΙΓΑ ΛΟΓΙΑ"}
                  </div>
                </div>
              </p.Stack>
            </p.Stack>
          </p.Stack>
          <Footer
            className={classNames("__wab_instance", sty.footer___7PVj2)}
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "button",
    "featureItem",
    "bestSellers",
    "productRow",
    "bigPlants",
    "cactuses"
  ],
  button: ["button"],
  featureItem: ["featureItem"],
  bestSellers: ["bestSellers", "productRow"],
  productRow: ["productRow"],
  bigPlants: ["bigPlants"],
  cactuses: ["cactuses"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  button: typeof Button;
  featureItem: typeof FeatureItem;
  bestSellers: "div";
  productRow: typeof ProductRow;
  bigPlants: "div";
  cactuses: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHome__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHome__VariantsArgs;
    args?: PlasmicHome__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHome__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicHome__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicHome__ArgProps,
          internalVariantPropNames: PlasmicHome__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHome__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHome";
  } else {
    func.displayName = `PlasmicHome.${nodeName}`;
  }
  return func;
}

export const PlasmicHome = Object.assign(
  // Top-level PlasmicHome renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    button: makeNodeComponent("button"),
    featureItem: makeNodeComponent("featureItem"),
    bestSellers: makeNodeComponent("bestSellers"),
    productRow: makeNodeComponent("productRow"),
    bigPlants: makeNodeComponent("bigPlants"),
    cactuses: makeNodeComponent("cactuses"),

    // Metadata about props expected for PlasmicHome
    internalVariantProps: PlasmicHome__VariantProps,
    internalArgProps: PlasmicHome__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHome;
/* prettier-ignore-end */
