// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: poSKmt1KMDoYUF6h3Y78GP
// Component: Ujl5y4BszvbjIC

import * as React from "react";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Header2 from "../../Header2"; // plasmic-import: hz3fKOWkD_JODa/component
import ProductCard from "../../ProductCard"; // plasmic-import: I9bSXDVKP-_xia/component
import Ratings from "../../Ratings"; // plasmic-import: RJoD3U13gzPVxR/component
import FeatureItem from "../../FeatureItem"; // plasmic-import: 6yeDc8BOoSwsCq/component
import BlogPost from "../../BlogPost"; // plasmic-import: XtW6OFg7bRL4Bi/component
import Footer from "../../Footer"; // plasmic-import: d3WHbEehslF7mk/component
import ProductRow from "../../ProductRow"; // plasmic-import: FaWqiAMedvRmIf/component

import { useScreenVariants as useScreenVariantsgW35LCmK5FyoDz } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: gW35LCmK5FYODz/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_library_plasmic_color_type_css from "../library_plasmic_color_type/plasmic_library_plasmic_color_type.module.css"; // plasmic-import: seaQhLVS4bbjiGvJJrRwyL/projectcss
import projectcss from "./plasmic_paradosiaki_agiografia.module.css"; // plasmic-import: poSKmt1KMDoYUF6h3Y78GP/projectcss
import sty from "./PlasmicStore.module.css"; // plasmic-import: Ujl5y4BszvbjIC/css

import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: -xYff7-eV79M4G/icon
import Icon2Icon from "./icons/PlasmicIcon__Icon2"; // plasmic-import: um22obSw4xOfIe/icon
import galinaNMiziNqvJx5MUnsplashjpgOj5FljDOxLgsNc from "./images/galinaNMiziNqvJx5MUnsplashjpg.jpg"; // plasmic-import: Oj5FljDOxLgsNC/picture
import igorSonFvPxCqgtwcUnsplashjpgDCWmzzZg7Jm1Ma from "./images/igorSonFvPxCqgtwcUnsplashjpg.jpg"; // plasmic-import: dCWmzzZg7Jm1MA/picture
import scottWebbORwRlTgBrPoUnsplashjpgK9B4Oe5CUewWz9 from "./images/scottWebbORwRlTgBrPoUnsplashjpg.jpg"; // plasmic-import: K9b4OE5CUewWZ9/picture
import freddieMarriageUcfKyTanLuUnsplashjpgSBkLuiwh6WxZe from "./images/freddieMarriageUcfKyTanLuUnsplashjpg.jpg"; // plasmic-import: SBkLuiwh-6wxZe/picture
import f18160GiZtf60VRv from "./images/f1.jpg"; // plasmic-import: 8160giZTF60vRV/picture
import f2HWMyZlVdy36Uxv from "./images/f2.jpg"; // plasmic-import: hWMyZLVdy36Uxv/picture
import f3CyKtk6OS2HjTfn from "./images/f3.jpg"; // plasmic-import: CyKTK6oS2HjTFN/picture
import f4MJjaldZdX2J0Ba from "./images/f4.jpg"; // plasmic-import: MJjaldZdX2J0Ba/picture
import b1ElV8NLvtMmEbJk from "./images/b1.jpg"; // plasmic-import: ElV8nLvtMMEbJk/picture
import b2CiXwhWWe0BHWc5 from "./images/b2.jpg"; // plasmic-import: CIXwhWWe0bHWc5/picture
import b3C6EpQzQg4ZOkm from "./images/b3.jpg"; // plasmic-import: c-6epQZQg4ZOkm/picture
import adidasNarnke4I0KdH from "./images/adidas.png"; // plasmic-import: NARNKE4_I0KD_H/picture
import hmZLzhFken3EtDtf from "./images/hm.png"; // plasmic-import: zLZHFken3etDtf/picture
import kappa1JEXpQ77XoIuTh from "./images/kappa.png"; // plasmic-import: 1jEXpQ77xoIuTh/picture
import lacosteJi0LZ1593W10 from "./images/lacoste.png"; // plasmic-import: Ji0l_z159-3W10/picture
import levisR9MIrqDlMzqOq from "./images/levis.png"; // plasmic-import: r9mIrqDLMzq_oq/picture
import plant6JpgWscOmZag54Ygk from "./images/plant6Jpg.png"; // plasmic-import: wscOmZag_54YGK/picture
import plant1JpgT9Rz1ZiHhgDik from "./images/plant1Jpg.png"; // plasmic-import: t9RZ-1ziHHGDik/picture
import plant5JpgY5X95TDvn16Wtz from "./images/plant5Jpg.png"; // plasmic-import: Y5X95tDvn16wtz/picture
import plant7JpgBapkTOSzUsAln from "./images/plant7Jpg.png"; // plasmic-import: BapkT_oSZUsALN/picture
import plant2Webp1FKgifHZnE3XC from "./images/plant2Webp.webp"; // plasmic-import: 1FKgifHZnE3x-C/picture
import plant41JpgGhCna01Pikt27V from "./images/plant41Jpg.png"; // plasmic-import: GHCna01pikt27v/picture
import plant31JpgYiWvMu6GjIxaZu from "./images/plant31Jpg.png"; // plasmic-import: YiWvMu6GJIxaZu/picture
import plant9WebpSeXEy1AwzRls23 from "./images/plant9Webp.webp"; // plasmic-import: SeXEy1AwzRLS23/picture

export type PlasmicStore__VariantMembers = {};
export type PlasmicStore__VariantsArgs = {};
type VariantPropType = keyof PlasmicStore__VariantsArgs;
export const PlasmicStore__VariantProps = new Array<VariantPropType>();

export type PlasmicStore__ArgsType = {};
type ArgPropType = keyof PlasmicStore__ArgsType;
export const PlasmicStore__ArgProps = new Array<ArgPropType>();

export type PlasmicStore__OverridesType = {
  root?: p.Flex<"div">;
  header?: p.Flex<"div">;
  header2?: p.Flex<typeof Header2>;
  featureItem?: p.Flex<typeof FeatureItem>;
  allProduct?: p.Flex<"div">;
  bigPlants?: p.Flex<"div">;
  cactuses?: p.Flex<"div">;
  bestSellers?: p.Flex<"div">;
  productRow?: p.Flex<typeof ProductRow>;
};

export interface DefaultStoreProps {
  className?: string;
}

const __wrapUserFunction =
  globalThis.__PlasmicWrapUserFunction ?? ((loc, fn) => fn());
const __wrapUserPromise =
  globalThis.__PlasmicWrapUserPromise ??
  (async (loc, promise) => {
    return await promise;
  });

function PlasmicStore__RenderFunc(props: {
  variants: PlasmicStore__VariantsArgs;
  args: PlasmicStore__ArgsType;
  overrides: PlasmicStore__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const [$queries, setDollarQueries] = React.useState({});

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsgW35LCmK5FyoDz()
  });

  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_library_plasmic_color_type_css.plasmic_tokens,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames(projectcss.all, sty.header)}
          >
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__pkXgx)}
            >
              <div className={classNames(projectcss.all, sty.freeBox__iExdq)}>
                {true ? (
                  <Header2
                    data-plasmic-name={"header2"}
                    data-plasmic-override={overrides.header2}
                    className={classNames("__wab_instance", sty.header2)}
                  />
                ) : null}
              </div>
            </p.Stack>
            {true ? (
              <div className={classNames(projectcss.all, sty.freeBox__oXgOz)}>
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2___5Exj2
                  )}
                >
                  {"Top Collections"}
                </h2>
              </div>
            ) : null}
            {true ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns___8NRae)}
              >
                <div className={classNames(projectcss.all, sty.column__gr3B)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__okoTp
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img___6LU3Q)}
                        displayHeight={"100%" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"none" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        src={{
                          src: galinaNMiziNqvJx5MUnsplashjpgOj5FljDOxLgsNc,
                          fullWidth: 1920,
                          fullHeight: 1278,
                          aspectRatio: undefined
                        }}
                      />
                    }
                    onSale={true}
                    price={"$65.00"}
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings__gpaOu
                        )}
                        numReviews={"(45 Review)"}
                      />
                    }
                    title={"Product"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column___9N7Z)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__txtC3
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__hSbmn)}
                        displayHeight={"100%" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"none" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        src={{
                          src: igorSonFvPxCqgtwcUnsplashjpgDCWmzzZg7Jm1Ma,
                          fullWidth: 640,
                          fullHeight: 481,
                          aspectRatio: undefined
                        }}
                      />
                    }
                    onSale={true}
                    price={"$80.00"}
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings__oVi7L
                        )}
                        numReviews={"(45 Review)"}
                      />
                    }
                    title={"Product"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__iQVf)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__n0EgB
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__bxFnI)}
                        displayHeight={"100%" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"none" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        src={{
                          src: scottWebbORwRlTgBrPoUnsplashjpgK9B4Oe5CUewWz9,
                          fullWidth: 1920,
                          fullHeight: 1280,
                          aspectRatio: undefined
                        }}
                      />
                    }
                    price={"$40.00"}
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings__i8E1
                        )}
                        numReviews={"(45 Review)"}
                      />
                    }
                    title={"Product"}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__lS42B)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__qv0Tt
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__imBid)}
                        displayHeight={"100%" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"none" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        src={{
                          src: freddieMarriageUcfKyTanLuUnsplashjpgSBkLuiwh6WxZe,
                          fullWidth: 640,
                          fullHeight: 427,
                          aspectRatio: undefined
                        }}
                      />
                    }
                    onSale={true}
                    price={"$100.00"}
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings__w8Lks
                        )}
                        numReviews={"(45 Review)"}
                      />
                    }
                    title={"Product"}
                  />
                </div>
              </p.Stack>
            ) : null}
            {true ? (
              <FeatureItem
                data-plasmic-name={"featureItem"}
                data-plasmic-override={overrides.featureItem}
                className={classNames("__wab_instance", sty.featureItem)}
              />
            ) : null}
            {true ? (
              <div className={classNames(projectcss.all, sty.freeBox__kd4U3)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__jRaP
                  )}
                >
                  {"Featured Products"}
                </div>
              </div>
            ) : null}
            {true ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns___7VoWy)}
              >
                <div className={classNames(projectcss.all, sty.column__nC0IZ)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__x1Zgu
                    )}
                    price={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__y0G0Z
                        )}
                      >
                        {"$160.00"}
                      </div>
                    }
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings__xxik3
                        )}
                        numReviews={"(12 Review)"}
                        stars={"two" as const}
                      />
                    }
                    title={
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__qz2Ku
                        )}
                      >
                        {"Designed Sofa"}
                      </div>
                    }
                    withReviews={true}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__vyY3I)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__t31Y1
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img___7IByf)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"none" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        src={{
                          src: f2HWMyZlVdy36Uxv,
                          fullWidth: 270,
                          fullHeight: 310,
                          aspectRatio: undefined
                        }}
                      />
                    }
                    price={"$200.00"}
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings__wpSt
                        )}
                        stars={"four" as const}
                      />
                    }
                    title={"Dining Table"}
                    withReviews={true}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column___2FYIa)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__a1Wp
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__mExI7)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"none" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        src={{
                          src: f3CyKtk6OS2HjTfn,
                          fullWidth: 270,
                          fullHeight: 310,
                          aspectRatio: undefined
                        }}
                      />
                    }
                    price={"$100.00"}
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings__lAxJe
                        )}
                        numReviews={"(23 Review)"}
                        stars={"five" as const}
                      />
                    }
                    title={"Chair and Table"}
                    withReviews={true}
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__pIcGa)}>
                  <ProductCard
                    className={classNames(
                      "__wab_instance",
                      sty.productCard__dsnKx
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__dvnWz)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"none" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        src={{
                          src: f4MJjaldZdX2J0Ba,
                          fullWidth: 270,
                          fullHeight: 310,
                          aspectRatio: undefined
                        }}
                      />
                    }
                    price={"$299.00"}
                    ratings={
                      <Ratings
                        className={classNames(
                          "__wab_instance",
                          sty.ratings__ltvB
                        )}
                        numReviews={"(35 Review)"}
                      />
                    }
                    title={"Modern Arm Chair"}
                    withReviews={true}
                  />
                </div>
              </p.Stack>
            ) : null}
            {true ? (
              <div className={classNames(projectcss.all, sty.freeBox___9Hnad)}>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__xBxmo
                  )}
                >
                  {"Latest Blog"}
                </div>
              </div>
            ) : null}
            {true ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns__znb4E)}
              >
                <div className={classNames(projectcss.all, sty.column___6K5Ho)}>
                  <BlogPost
                    className={classNames("__wab_instance", sty.blogPost__wYyB)}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__zoP3E)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"none" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        src={{
                          src: b1ElV8NLvtMmEbJk,
                          fullWidth: 370,
                          fullHeight: 250,
                          aspectRatio: undefined
                        }}
                      />
                    }
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__mdbaf)}>
                  <BlogPost
                    className={classNames(
                      "__wab_instance",
                      sty.blogPost__sDbi0
                    )}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img___94XPm)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"none" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        src={{
                          src: b2CiXwhWWe0BHWc5,
                          fullWidth: 370,
                          fullHeight: 250,
                          aspectRatio: undefined
                        }}
                      />
                    }
                  />
                </div>
                <div className={classNames(projectcss.all, sty.column__ulPXy)}>
                  <BlogPost
                    className={classNames("__wab_instance", sty.blogPost___7Th)}
                    image={
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__u3Syx)}
                        displayHeight={"auto" as const}
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"none" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        src={{
                          src: b3C6EpQzQg4ZOkm,
                          fullWidth: 370,
                          fullHeight: 250,
                          aspectRatio: undefined
                        }}
                      />
                    }
                  />
                </div>
              </p.Stack>
            ) : null}
            {true ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__cJXgA)}
              >
                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__cqPPj)}
                  displayHeight={"60px" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"none" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"90px" as const}
                  src={{
                    src: adidasNarnke4I0KdH,
                    fullWidth: 90,
                    fullHeight: 60,
                    aspectRatio: undefined
                  }}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__w7LFe)}
                  displayHeight={"60px" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"none" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"91px" as const}
                  src={{
                    src: hmZLzhFken3EtDtf,
                    fullWidth: 91,
                    fullHeight: 60,
                    aspectRatio: undefined
                  }}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__vXLw)}
                  displayHeight={"60px" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"none" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"98px" as const}
                  src={{
                    src: kappa1JEXpQ77XoIuTh,
                    fullWidth: 98,
                    fullHeight: 60,
                    aspectRatio: undefined
                  }}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img___5VomR)}
                  displayHeight={"60px" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"none" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"124px" as const}
                  src={{
                    src: lacosteJi0LZ1593W10,
                    fullWidth: 124,
                    fullHeight: 60,
                    aspectRatio: undefined
                  }}
                />

                <p.PlasmicImg
                  alt={""}
                  className={classNames(sty.img__z5RxN)}
                  displayHeight={"60px" as const}
                  displayMaxHeight={"none" as const}
                  displayMaxWidth={"none" as const}
                  displayMinHeight={"0" as const}
                  displayMinWidth={"0" as const}
                  displayWidth={"125px" as const}
                  src={{
                    src: levisR9MIrqDlMzqOq,
                    fullWidth: 125,
                    fullHeight: 60,
                    aspectRatio: undefined
                  }}
                />
              </p.Stack>
            ) : null}
            {true ? (
              <Footer
                className={classNames("__wab_instance", sty.footer__wUqDu)}
              />
            ) : null}
          </div>
          {true ? (
            <div
              data-plasmic-name={"allProduct"}
              data-plasmic-override={overrides.allProduct}
              className={classNames(projectcss.all, sty.allProduct)}
            >
              {true ? (
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___1NlbH)}
                >
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__aMdtQ
                    )}
                  >
                    {"All Products"}
                  </h2>
                </p.Stack>
              ) : null}
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns__buqlW)}
              >
                <div className={classNames(projectcss.all, sty.column__waSzr)}>
                  {true ? (
                    <div
                      className={classNames(projectcss.all, sty.freeBox__ldZsZ)}
                    >
                      {true ? (
                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__gtiKl
                          )}
                        >
                          <a
                            className={classNames(
                              projectcss.all,
                              projectcss.a,
                              projectcss.__wab_text,
                              sty.link__u0Yk
                            )}
                          >
                            {"Summer plants"}
                          </a>
                          <a
                            className={classNames(
                              projectcss.all,
                              projectcss.a,
                              projectcss.__wab_text,
                              sty.link__j5So
                            )}
                          >
                            {"Plants from Europe"}
                          </a>
                          <a
                            className={classNames(
                              projectcss.all,
                              projectcss.a,
                              projectcss.__wab_text,
                              sty.link__fqQNi
                            )}
                          >
                            {"Cactuses"}
                          </a>
                          <a
                            className={classNames(
                              projectcss.all,
                              projectcss.a,
                              projectcss.__wab_text,
                              sty.link__xuSiR
                            )}
                          >
                            {"Big plants"}
                          </a>
                        </p.Stack>
                      ) : null}
                    </div>
                  ) : null}
                </div>
                <div className={classNames(projectcss.all, sty.column__sKvGg)}>
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.columns__tW0VB)}
                  >
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.column__h32Cq)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__hAbU)}
                        displayHeight={
                          "270px /* plasmic-token: PE1QFaZ5ZFDg60 */" as const
                        }
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        loading={"lazy" as const}
                        src={{
                          src: plant6JpgWscOmZag54Ygk,
                          fullWidth: 400,
                          fullHeight: 400,
                          aspectRatio: undefined
                        }}
                      />

                      {true ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__u4IeJ
                          )}
                        >
                          <Icon3Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__lqh7I
                            )}
                            role={"img"}
                          />
                        </div>
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__dPbrr
                        )}
                      >
                        <a
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            projectcss.__wab_text,
                            sty.link__kpi2O
                          )}
                        >
                          {"Donec finibus"}
                        </a>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__ciWm2
                          )}
                        >
                          {"bigplants"}
                        </div>
                        <h5
                          className={classNames(
                            projectcss.all,
                            projectcss.h5,
                            projectcss.__wab_text,
                            sty.h5__aHKc
                          )}
                        >
                          {"$100.00"}
                        </h5>
                      </div>
                    </p.Stack>
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.column__z7QyH)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__kPkGt)}
                        displayHeight={
                          "270px /* plasmic-token: PE1QFaZ5ZFDg60 */" as const
                        }
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        loading={"lazy" as const}
                        src={{
                          src: plant1JpgT9Rz1ZiHhgDik,
                          fullWidth: 400,
                          fullHeight: 400,
                          aspectRatio: undefined
                        }}
                      />

                      {true ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__dysq
                          )}
                        >
                          <Icon3Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__i8RJx
                            )}
                            role={"img"}
                          />
                        </div>
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__fsqo
                        )}
                      >
                        <a
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            projectcss.__wab_text,
                            sty.link__ismwo
                          )}
                        >
                          {"Nulla suscipit"}
                        </a>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__uZcKz
                          )}
                        >
                          {"bigplants "}
                        </div>
                        <h5
                          className={classNames(
                            projectcss.all,
                            projectcss.h5,
                            projectcss.__wab_text,
                            sty.h5__xA9Sl
                          )}
                        >
                          {"$49.40 "}
                        </h5>
                      </div>
                    </p.Stack>
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.column__en0A0)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img___5UfQx)}
                        displayHeight={
                          "270px /* plasmic-token: PE1QFaZ5ZFDg60 */" as const
                        }
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        loading={"lazy" as const}
                        src={{
                          src: plant5JpgY5X95TDvn16Wtz,
                          fullWidth: 400,
                          fullHeight: 400,
                          aspectRatio: undefined
                        }}
                      />

                      {true ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__z7Zb8
                          )}
                        >
                          <Icon3Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__hTam9
                            )}
                            role={"img"}
                          />
                        </div>
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__g7LG
                        )}
                      >
                        <a
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            projectcss.__wab_text,
                            sty.link__sabRx
                          )}
                        >
                          {"Vestibulum eget"}
                        </a>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__iR4Q
                          )}
                        >
                          {"bigplants "}
                        </div>
                        <h5
                          className={classNames(
                            projectcss.all,
                            projectcss.h5,
                            projectcss.__wab_text,
                            sty.h5___1XPT
                          )}
                        >
                          {"$220.40 "}
                        </h5>
                      </div>
                    </p.Stack>
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.column__j5X3I)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__fMu7)}
                        displayHeight={
                          "270px /* plasmic-token: PE1QFaZ5ZFDg60 */" as const
                        }
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        loading={"lazy" as const}
                        src={{
                          src: plant7JpgBapkTOSzUsAln,
                          fullWidth: 400,
                          fullHeight: 400,
                          aspectRatio: undefined
                        }}
                      />

                      {true ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__ug6C
                          )}
                        >
                          <Icon3Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__dtm4R
                            )}
                            role={"img"}
                          />
                        </div>
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__krQfy
                        )}
                      >
                        <a
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            projectcss.__wab_text,
                            sty.link___6PdT5
                          )}
                        >
                          {"Sed consectetur"}
                        </a>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__kJmPg
                          )}
                        >
                          {"bigplants "}
                        </div>
                        <h5
                          className={classNames(
                            projectcss.all,
                            projectcss.h5,
                            projectcss.__wab_text,
                            sty.h5__yPqS
                          )}
                        >
                          {"$18.40 "}
                        </h5>
                      </div>
                    </p.Stack>
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.column__pj9Dr)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__otmu4)}
                        displayHeight={
                          "270px /* plasmic-token: PE1QFaZ5ZFDg60 */" as const
                        }
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        loading={"lazy" as const}
                        src={{
                          src: plant6JpgWscOmZag54Ygk,
                          fullWidth: 400,
                          fullHeight: 400,
                          aspectRatio: undefined
                        }}
                      />

                      {true ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox___4Ab4Q
                          )}
                        >
                          <Icon3Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__soxKs
                            )}
                            role={"img"}
                          />
                        </div>
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__zgd1G
                        )}
                      >
                        <a
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            projectcss.__wab_text,
                            sty.link__ucHrJ
                          )}
                        >
                          {"Donec finibus"}
                        </a>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__qcWyk
                          )}
                        >
                          {"bigplants"}
                        </div>
                        <h5
                          className={classNames(
                            projectcss.all,
                            projectcss.h5,
                            projectcss.__wab_text,
                            sty.h5__blqqb
                          )}
                        >
                          {"$100.00"}
                        </h5>
                      </div>
                    </p.Stack>
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.column__gyUnt)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__aRnkO)}
                        displayHeight={
                          "270px /* plasmic-token: PE1QFaZ5ZFDg60 */" as const
                        }
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        loading={"lazy" as const}
                        src={{
                          src: plant2Webp1FKgifHZnE3XC,
                          fullWidth: 400,
                          fullHeight: 400,
                          aspectRatio: undefined
                        }}
                      />

                      {true ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__hrEiG
                          )}
                        >
                          <Icon3Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__aTu5E
                            )}
                            role={"img"}
                          />
                        </div>
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__vz5Tm
                        )}
                      >
                        <a
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            projectcss.__wab_text,
                            sty.link___97OTu
                          )}
                        >
                          {"Integer porta"}
                        </a>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__eHc7
                          )}
                        >
                          {"Cactuses"}
                        </div>
                        <h5
                          className={classNames(
                            projectcss.all,
                            projectcss.h5,
                            projectcss.__wab_text,
                            sty.h5__nPrsE
                          )}
                        >
                          {"$49.40 "}
                        </h5>
                      </div>
                    </p.Stack>
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.column__pTnZe)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img___4YH7)}
                        displayHeight={
                          "270px /* plasmic-token: PE1QFaZ5ZFDg60 */" as const
                        }
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        loading={"lazy" as const}
                        src={{
                          src: plant41JpgGhCna01Pikt27V,
                          fullWidth: 400,
                          fullHeight: 400,
                          aspectRatio: undefined
                        }}
                      />

                      {true ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox___0Eb78
                          )}
                        >
                          <Icon3Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__gsf9N
                            )}
                            role={"img"}
                          />
                        </div>
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__pgMLu
                        )}
                      >
                        <a
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            projectcss.__wab_text,
                            sty.link__heakz
                          )}
                        >
                          {"Cras molestie"}
                        </a>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__ewMy9
                          )}
                        >
                          {"cactuses "}
                        </div>
                        <h5
                          className={classNames(
                            projectcss.all,
                            projectcss.h5,
                            projectcss.__wab_text,
                            sty.h5__ljDk6
                          )}
                        >
                          {"$24.99"}
                        </h5>
                      </div>
                    </p.Stack>
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.column__nagh9)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__iWtgA)}
                        displayHeight={
                          "270px /* plasmic-token: PE1QFaZ5ZFDg60 */" as const
                        }
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        loading={"lazy" as const}
                        src={{
                          src: plant31JpgYiWvMu6GjIxaZu,
                          fullWidth: 400,
                          fullHeight: 400,
                          aspectRatio: undefined
                        }}
                      />

                      {true ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__snEqq
                          )}
                        >
                          <Icon3Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__cwjE0
                            )}
                            role={"img"}
                          />
                        </div>
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__d52Sk
                        )}
                      >
                        <a
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            projectcss.__wab_text,
                            sty.link__eZgEi
                          )}
                        >
                          {"Curabitur eu tempor"}
                        </a>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__pedpG
                          )}
                        >
                          {"Cactuses"}
                        </div>
                        <h5
                          className={classNames(
                            projectcss.all,
                            projectcss.h5,
                            projectcss.__wab_text,
                            sty.h5__cIbNj
                          )}
                        >
                          {"$49.40 "}
                        </h5>
                      </div>
                    </p.Stack>
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(projectcss.all, sty.column__c7PFu)}
                    >
                      <p.PlasmicImg
                        alt={""}
                        className={classNames(sty.img__usIrm)}
                        displayHeight={
                          "270px /* plasmic-token: PE1QFaZ5ZFDg60 */" as const
                        }
                        displayMaxHeight={"none" as const}
                        displayMaxWidth={"100%" as const}
                        displayMinHeight={"0" as const}
                        displayMinWidth={"0" as const}
                        displayWidth={"100%" as const}
                        loading={"lazy" as const}
                        src={{
                          src: plant9WebpSeXEy1AwzRls23,
                          fullWidth: 400,
                          fullHeight: 400,
                          aspectRatio: undefined
                        }}
                      />

                      {true ? (
                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__cZsPv
                          )}
                        >
                          <Icon3Icon
                            className={classNames(
                              projectcss.all,
                              sty.svg__vrjsH
                            )}
                            role={"img"}
                          />
                        </div>
                      ) : null}
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__mv1Bw
                        )}
                      >
                        <a
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            projectcss.__wab_text,
                            sty.link___5Q2ZI
                          )}
                        >
                          {"Fusce sagittis"}
                        </a>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___3CFgE
                          )}
                        >
                          {"Cactuses"}
                        </div>
                        <h5
                          className={classNames(
                            projectcss.all,
                            projectcss.h5,
                            projectcss.__wab_text,
                            sty.h5__sxIh
                          )}
                        >
                          {"$49.40 "}
                        </h5>
                      </div>
                    </p.Stack>
                  </p.Stack>
                </div>
              </p.Stack>
            </div>
          ) : null}
          {true ? (
            <p.Stack
              as={"div"}
              data-plasmic-name={"bigPlants"}
              data-plasmic-override={overrides.bigPlants}
              hasGap={true}
              className={classNames(projectcss.all, sty.bigPlants)}
            >
              {true ? (
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___298Ak)}
                >
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__ryLiz
                    )}
                  >
                    {"Big plants"}
                  </h2>
                </p.Stack>
              ) : null}
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns__xRk91)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.column___2SNnC)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__iyhBt)}
                    displayHeight={
                      "270px /* plasmic-token: PE1QFaZ5ZFDg60 */" as const
                    }
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"100%" as const}
                    loading={"lazy" as const}
                    src={{
                      src: plant6JpgWscOmZag54Ygk,
                      fullWidth: 400,
                      fullHeight: 400,
                      aspectRatio: undefined
                    }}
                  />

                  {true ? (
                    <div
                      className={classNames(projectcss.all, sty.freeBox__yxYi1)}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg__lNxcd)}
                        role={"img"}
                      />
                    </div>
                  ) : null}
                  <div
                    className={classNames(projectcss.all, sty.freeBox__hSkMp)}
                  >
                    <a
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__ejsqw
                      )}
                    >
                      {"Donec finibus"}
                    </a>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__pYqkU
                      )}
                    >
                      {"bigplants"}
                    </div>
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5__c1Dt
                      )}
                    >
                      {"$100.00"}
                    </h5>
                  </div>
                </p.Stack>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.column__krcSg)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__zZcJp)}
                    displayHeight={
                      "270px /* plasmic-token: PE1QFaZ5ZFDg60 */" as const
                    }
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"100%" as const}
                    loading={"lazy" as const}
                    src={{
                      src: plant1JpgT9Rz1ZiHhgDik,
                      fullWidth: 400,
                      fullHeight: 400,
                      aspectRatio: undefined
                    }}
                  />

                  {true ? (
                    <div
                      className={classNames(projectcss.all, sty.freeBox__fpITy)}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg__oaO71)}
                        role={"img"}
                      />
                    </div>
                  ) : null}
                  <div
                    className={classNames(projectcss.all, sty.freeBox__b755S)}
                  >
                    <a
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__gb3Bb
                      )}
                    >
                      {"Nulla suscipit"}
                    </a>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__cLv
                      )}
                    >
                      {"bigplants "}
                    </div>
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5__v25S
                      )}
                    >
                      {"$49.40 "}
                    </h5>
                  </div>
                </p.Stack>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.column___1MbQq)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__jsXfn)}
                    displayHeight={
                      "270px /* plasmic-token: PE1QFaZ5ZFDg60 */" as const
                    }
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"100%" as const}
                    loading={"lazy" as const}
                    src={{
                      src: plant7JpgBapkTOSzUsAln,
                      fullWidth: 400,
                      fullHeight: 400,
                      aspectRatio: undefined
                    }}
                  />

                  {true ? (
                    <div
                      className={classNames(projectcss.all, sty.freeBox__z3Dmo)}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg__mmi6X)}
                        role={"img"}
                      />
                    </div>
                  ) : null}
                  <div
                    className={classNames(projectcss.all, sty.freeBox__v7HdN)}
                  >
                    <a
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__h616C
                      )}
                    >
                      {"Sed consectetur"}
                    </a>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__bUZmA
                      )}
                    >
                      {"bigplants "}
                    </div>
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5__ejz7P
                      )}
                    >
                      {"$18.40 "}
                    </h5>
                  </div>
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__dnaaA)}
                    displayHeight={
                      "270px /* plasmic-token: PE1QFaZ5ZFDg60 */" as const
                    }
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"100%" as const}
                    loading={"lazy" as const}
                    src={{
                      src: plant5JpgY5X95TDvn16Wtz,
                      fullWidth: 400,
                      fullHeight: 400,
                      aspectRatio: undefined
                    }}
                  />

                  {true ? (
                    <div
                      className={classNames(projectcss.all, sty.freeBox__pC2Nh)}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg___0EZoy)}
                        role={"img"}
                      />
                    </div>
                  ) : null}
                  <div
                    className={classNames(projectcss.all, sty.freeBox__nVn3W)}
                  >
                    <a
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link___0HVeg
                      )}
                    >
                      {"Vestibulum eget"}
                    </a>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__coEaW
                      )}
                    >
                      {"bigplants "}
                    </div>
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5___9O25K
                      )}
                    >
                      {"$220.40 "}
                    </h5>
                  </div>
                </p.Stack>
              </p.Stack>
            </p.Stack>
          ) : null}
          {true ? (
            <p.Stack
              as={"div"}
              data-plasmic-name={"cactuses"}
              data-plasmic-override={overrides.cactuses}
              hasGap={true}
              className={classNames(projectcss.all, sty.cactuses)}
            >
              {true ? (
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__mISzC)}
                >
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__hxGam
                    )}
                  >
                    {"Cactuses"}
                  </h2>
                </p.Stack>
              ) : null}
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns__wkJRb)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.column__qDmwH)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img___0X8Zy)}
                    displayHeight={
                      "270px /* plasmic-token: PE1QFaZ5ZFDg60 */" as const
                    }
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"100%" as const}
                    loading={"lazy" as const}
                    src={{
                      src: plant41JpgGhCna01Pikt27V,
                      fullWidth: 400,
                      fullHeight: 400,
                      aspectRatio: undefined
                    }}
                  />

                  {true ? (
                    <div
                      className={classNames(projectcss.all, sty.freeBox__iclQr)}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg__baAw8)}
                        role={"img"}
                      />
                    </div>
                  ) : null}
                  <div
                    className={classNames(projectcss.all, sty.freeBox__np9Mn)}
                  >
                    <a
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__xpWa
                      )}
                    >
                      {"Cras molestie"}
                    </a>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___3R5Zx
                      )}
                    >
                      {"cactuses "}
                    </div>
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5__gfobW
                      )}
                    >
                      {"$24.99"}
                    </h5>
                  </div>
                </p.Stack>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.column__uUrsf)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__kjZv)}
                    displayHeight={
                      "270px /* plasmic-token: PE1QFaZ5ZFDg60 */" as const
                    }
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"100%" as const}
                    loading={"lazy" as const}
                    src={{
                      src: plant31JpgYiWvMu6GjIxaZu,
                      fullWidth: 400,
                      fullHeight: 400,
                      aspectRatio: undefined
                    }}
                  />

                  {true ? (
                    <div
                      className={classNames(projectcss.all, sty.freeBox__cz91A)}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg__s2WcD)}
                        role={"img"}
                      />
                    </div>
                  ) : null}
                  <div
                    className={classNames(projectcss.all, sty.freeBox__tew1U)}
                  >
                    <a
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__mWeza
                      )}
                    >
                      {"Curabitur eu tempor"}
                    </a>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___2O18F
                      )}
                    >
                      {"Cactuses"}
                    </div>
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5___1EJ0N
                      )}
                    >
                      {"$49.40 "}
                    </h5>
                  </div>
                </p.Stack>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.column__u00Ah)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__fNm7L)}
                    displayHeight={
                      "270px /* plasmic-token: PE1QFaZ5ZFDg60 */" as const
                    }
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"100%" as const}
                    loading={"lazy" as const}
                    src={{
                      src: plant9WebpSeXEy1AwzRls23,
                      fullWidth: 400,
                      fullHeight: 400,
                      aspectRatio: undefined
                    }}
                  />

                  {true ? (
                    <div
                      className={classNames(projectcss.all, sty.freeBox__dn3Ea)}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg__czbxa)}
                        role={"img"}
                      />
                    </div>
                  ) : null}
                  <div
                    className={classNames(projectcss.all, sty.freeBox__ts98P)}
                  >
                    <a
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__iqCbu
                      )}
                    >
                      {"Fusce sagittis"}
                    </a>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__lq4J
                      )}
                    >
                      {"Fusce sagittis"}
                    </div>
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5__aWzNl
                      )}
                    >
                      {"$49.40 "}
                    </h5>
                  </div>
                </p.Stack>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.column__wmj0)}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__ekrXn)}
                    displayHeight={
                      "270px /* plasmic-token: PE1QFaZ5ZFDg60 */" as const
                    }
                    displayMaxHeight={"none" as const}
                    displayMaxWidth={"100%" as const}
                    displayMinHeight={"0" as const}
                    displayMinWidth={"0" as const}
                    displayWidth={"100%" as const}
                    loading={"lazy" as const}
                    src={{
                      src: plant2Webp1FKgifHZnE3XC,
                      fullWidth: 400,
                      fullHeight: 400,
                      aspectRatio: undefined
                    }}
                  />

                  {true ? (
                    <div
                      className={classNames(projectcss.all, sty.freeBox__fxHin)}
                    >
                      <Icon3Icon
                        className={classNames(projectcss.all, sty.svg__rxTSp)}
                        role={"img"}
                      />
                    </div>
                  ) : null}
                  <div
                    className={classNames(projectcss.all, sty.freeBox__pKm3H)}
                  >
                    <a
                      className={classNames(
                        projectcss.all,
                        projectcss.a,
                        projectcss.__wab_text,
                        sty.link__nG3KQ
                      )}
                    >
                      {"Integer porta"}
                    </a>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__xa02V
                      )}
                    >
                      {"Cactuses"}
                    </div>
                    <h5
                      className={classNames(
                        projectcss.all,
                        projectcss.h5,
                        projectcss.__wab_text,
                        sty.h5__zxLuy
                      )}
                    >
                      {"$49.40 "}
                    </h5>
                  </div>
                </p.Stack>
              </p.Stack>
            </p.Stack>
          ) : null}
          <p.Stack
            as={"div"}
            data-plasmic-name={"bestSellers"}
            data-plasmic-override={overrides.bestSellers}
            hasGap={true}
            className={classNames(projectcss.all, sty.bestSellers)}
          >
            {true ? (
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__oiKx2)}
              >
                <Icon2Icon
                  className={classNames(projectcss.all, sty.svg__hoH5L)}
                  role={"img"}
                />

                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__aumI
                  )}
                >
                  {"Best sellers"}
                </h2>
              </p.Stack>
            ) : null}
            {true ? (
              <ProductRow
                data-plasmic-name={"productRow"}
                data-plasmic-override={overrides.productRow}
                className={classNames("__wab_instance", sty.productRow)}
              />
            ) : null}
          </p.Stack>
          <Footer className={classNames("__wab_instance", sty.footer__xo9Ee)} />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "header",
    "header2",
    "featureItem",
    "allProduct",
    "bigPlants",
    "cactuses",
    "bestSellers",
    "productRow"
  ],
  header: ["header", "header2", "featureItem"],
  header2: ["header2"],
  featureItem: ["featureItem"],
  allProduct: ["allProduct"],
  bigPlants: ["bigPlants"],
  cactuses: ["cactuses"],
  bestSellers: ["bestSellers", "productRow"],
  productRow: ["productRow"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  header: "div";
  header2: typeof Header2;
  featureItem: typeof FeatureItem;
  allProduct: "div";
  bigPlants: "div";
  cactuses: "div";
  bestSellers: "div";
  productRow: typeof ProductRow;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicStore__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicStore__VariantsArgs;
    args?: PlasmicStore__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicStore__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicStore__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicStore__ArgProps,
          internalVariantPropNames: PlasmicStore__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicStore__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicStore";
  } else {
    func.displayName = `PlasmicStore.${nodeName}`;
  }
  return func;
}

export const PlasmicStore = Object.assign(
  // Top-level PlasmicStore renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    header2: makeNodeComponent("header2"),
    featureItem: makeNodeComponent("featureItem"),
    allProduct: makeNodeComponent("allProduct"),
    bigPlants: makeNodeComponent("bigPlants"),
    cactuses: makeNodeComponent("cactuses"),
    bestSellers: makeNodeComponent("bestSellers"),
    productRow: makeNodeComponent("productRow"),

    // Metadata about props expected for PlasmicStore
    internalVariantProps: PlasmicStore__VariantProps,
    internalArgProps: PlasmicStore__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicStore;
/* prettier-ignore-end */
